### ISSUE TITLE
靶机测试

### ISSUE THREAD

**Issue by aoeeeeeee** [wa1ki0g/xsshelp-py#1]
测试皮卡丘，没有扫到漏洞诶

**Comment by wa1ki0g** [comment]
这个是挖src的一种思路，不是那种纯漏扫的，这个的原理就是提取页面中的标签的参数，然后发请求，看一些参数是不是会显示在页面上，如果会显示到的话，再接着手动测试

**Comment by aoeeeeeee** [comment]
谢谢解答！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月21日(星期四) 下午4:42
收件人: "wa1ki0g/xsshelp-py";
抄送: "Author";
主题: Re: [wa1ki0g/xsshelp-py] 靶机测试 (Issue #1)





 
这个是挖src的一种思路，不是那种纯漏扫的，这个的原理就是提取页面中的标签的参数，然后发请求，看一些参数是不是会显示在页面上，如果会显示到的话，再接着手动测试
 
&mdash;
